version: "3.9"

networks:
  backend:
    driver: bridge
    name: golang-url-shortener_backend

volumes:
  postgres:
    driver: local

services:

### golang ####################
  golang:
    image: golang:1.18.1-alpine
    working_dir: /server
    volumes:
      - .:/server
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    entrypoint: go run main.go
    restart: always
    networks:
      - backend

### postgres ####################
  postgres:
    image: postgres:14.2-alpine
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata
    restart: always
    networks:
      - backend